# Site settings
title: Tuba's Visual Arts Portfolio
email: tubakutluuu@gmail.com
description: >
  An IB student based in Ankara Turkey. Mostly inspired by people with different features as a symbol of different perspectives on life and cats of course.
instagram_username: tuba_kutluu
linkedin_username_full: tuba-kutlu-5ab204205
linkedin_username_display: Tuba Kutlu
spotify_username_display: tub
spotify_username_full: 21wtyjlfptxexfyzuijudtnva?si=735a7dbd47494899
github_username:  tubakutluu

# Build settings
markdown: kramdown
permalink: pretty
